SecretShareAjax/config/routes.rb
SecretShareAjax::Application.routes.draw do
  root :to => "users#show"

  resources :secrets, :only => [:create]
  resources :users, :only => [:create, :new, :show, :index] do
    resources :secrets, :only => [:new]
    resource :friendship, :only => [:create, :destroy]
    resources :friendships, :only => [:index]
  end
  resource :session, :only => [:create, :destroy, :new]

  get '/error' => 'users#error'
end

SecretShareAjax/app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :out_friend_id, :in_friend_id

  validates :out_friend_id, :in_friend_id, :presence => true
  validates :out_friend_id, :uniqueness => { :scope => :in_friend_id }

  belongs_to :out_friend, :class_name => "User"
  belongs_to :in_friend, :class_name => "User"

  def self.can_friend?(out_friend_id, in_friend_id)
    return false if out_friend_id == in_friend_id
    !Friendship.exists?(:out_friend_id => out_friend_id, :in_friend_id => in_friend_id)
  end

  def self.can_unfriend?(out_friend_id, in_friend_id)
    Friendship.exists?(:out_friend_id => out_friend_id, :in_friend_id => in_friend_id)
  end
end

SecretShareAjax/app/models/secret.rb
class Secret < ActiveRecord::Base
  attr_accessible :author_id, :recipient_id, :title, :tag_ids
  validates :author_id, :recipient_id, :title, :presence => true

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"

  has_many :secret_taggings, class_name: 'SecretTagging'
  has_many :tags, through: :secret_taggings

end

SecretShareAjax/app/models/secret_tagging.rb
class SecretTagging < ActiveRecord::Base
  attr_accessible :secret_id, :tag_id
  validates :secret_id, :tag_id, presence: true

  belongs_to :secret, class_name: 'Secret'
  belongs_to :tag, class_name: 'Tag'

end

SecretShareAjax/app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true

  has_many :secret_taggings, class_name: 'SecretTagging'
  has_many :tagged_secrets, :through => :secret_taggings, :source => :secret
end

SecretShareAjax/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :author_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )

  has_many :friendships, :class_name => "Friendship", :foreign_key => :in_friend_id
  has_many :friends, through: :friendships, source: :in_friend

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  def secrets_sent(recipient)
    Secret.where(:author_id => self.id, :recipient_id => recipient.id)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

SecretShareAjax/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

SecretShareAjax/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friends = current_user.friends
    render :index
  end

  def create
    @friendship = Friendship.new()
    @friendship.in_friend_id = current_user.id
    @friendship.out_friend_id = params[:user_id]
    @friendship.save!
    render :json => @friendship
  end

  def destroy
    @friendship = Friendship.find_by_in_friend_id_and_out_friend_id(current_user.id, params[:user_id])
    @friendship.destroy
    head :ok
  end
end

SecretShareAjax/app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def new
    @secret = Secret.new
    @user_id = params[:user_id]
    render :new
  end

  def create
    @secret = Secret.new(params[:secret])
    @secret.author_id = current_user.id

    if @secret.save
      render :json => @secret
    else
      # flash[:error] = @secret.errors.full_messages
      # redirect_to user_url(params[:secret][:recipient_id])
      render :text => @secret.errors.full_messages.join(" "), :status => 422
    end
  end
end

SecretShareAjax/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

SecretShareAjax/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def index
    @users = User.all
    render :index
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
      @user_id = params[:id]
      render :show
    else
      redirect_to user_url(current_user)
    end
  end

  def error
    render :json => { error_message: 'hello' }, :status => 422
  end
end

SecretShareAjax/app/helpers/application_helper.rb
module ApplicationHelper
end

SecretShareAjax/app/helpers/friendships_helper.rb
module FriendshipsHelper
end

SecretShareAjax/app/helpers/secrets_helper.rb
module SecretsHelper
end

SecretShareAjax/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

SecretShareAjax/app/helpers/users_helper.rb
module UsersHelper
end

SecretShareAjax/app/views/friendships/index.html.erb
<h1>My friends</h1>
<ul>
<% @friends.each do |friend| %>
	<li><%= friend.username %></li>
<% end %>
</ul>

SecretShareAjax/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<script type="text/javascript" src="/jquery.serializeJSON.min.js"></script>
	<script type="text/javascript" src="/underscore-min.js"></script>

</head>

<body>

<div id="header">
	<div id="title">
		<h1>SecretShare</h1>
	</div>
<% if !current_user.nil? %>
	<div id="user-info">
		Logged in as: <%= current_user.username %>
		<%= button_to "Logout", session_url, :method => :delete %>
	</div>
<% end %>
</div>

<div id="sidebar">
	<ul>
		<li><%= link_to "My Secrets", user_url(current_user) %></li>
		<li><%= link_to "My Friends", user_friendships_url(current_user) %></li>
		<li><%= link_to "Add Friends", users_url %></li>
	</ul>
</div>

<div id="main">
<%= yield %>
</div>

</body>
</html>

SecretShareAjax/app/views/secrets/_form.html.erb
<form id="secret-form" action="<%= secrets_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="hidden" name="secret[recipient_id]" value="<%= user_id %>">

	<div id="error-message"></div>

	<label for="secret_title">Title</label>
	<input type="text" name="secret[title]" id="secret_title"><br>

	<label>Tags</label>
	<div id="secret-tag-select"></div>
	<%= link_to "Add another tag", "#", :id => "add-tag" %>
	<p><input type="submit" value="Create"></p>
</form>

<script type="application/json" id="tags">
	{ "tags": <%= Tag.all.to_json.html_safe %> }
</script>

<script type="text/template" id="tags-template">
	<select id="secret_tag_ids" name="secret[tag_ids][]">
	<option value=""> </option>
	<%% _(tags).each(function (tag) { %>
		<option value="<%%= tag.id %>"><%%= tag.name %></option>
	<%%	}) %>
	</select><br>
</script>

<script type="application/javascript">
	var tags = JSON.parse($('#tags').html()).tags;
	var templateCode = $('#tags-template').html();
	var templateFn = _.template(templateCode);
	var selectOptions = templateFn({ tags: tags });
	var addSelect = function () {
		$('#secret-tag-select').append(selectOptions);
	};

	addSelect();

	$('#add-tag').on('click', function (e) {
		e.preventDefault();
		addSelect();
	});

	$('#secret-form').on('submit', function (event) {
		event.preventDefault();
		var formData = $('#secret-form').serializeJSON();
		$.ajax({
			type: "post",
			url: "/secrets",
			data: formData,
			success: function (data) {
				event.currentTarget.reset();
				$('ul#secrets').append($('<li>' + data.title + '</li>'));
				$('#secret-tag-select').empty();
				addSelect();
			},
			error: function (a) {
				$("#error-message").text(a.responseText);
			}
		})
	})
</script>

SecretShareAjax/app/views/secrets/new.html.erb
<h1>New Secret</h1>

<%= render "form", user_id: @user_id %>

SecretShareAjax/app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

SecretShareAjax/app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
<% @users.each do |user| %>
<li><%= user.username %>
	<% friendship_class ||=
	(Friendship.can_friend?(user.id, current_user.id) ? "can-friend" : nil) %>
	<% friendship_class ||=
	(Friendship.can_unfriend?(user.id, current_user.id) ? "can-unfriend" : nil) %>
	<div class="friend-buttons <%= friendship_class %>">
		<%= button_to "Add Friend", user_friendship_url(user.id),
																:method => :post,
																:class => :friend,
																:data => { 'id' => user.id } %>

		<%= button_to "Unfriend", user_friendship_url(user.id),
																:method => :delete,
																:class => :unfriend,
																:data => { 'id' => user.id } %>
    </div>
	</li>
<% end %>
</ul>

<script type="text/javascript">
$(".friend").on("click", function (event) {
	var button = $(event.currentTarget);
	var user_id = button.data("id");
	button.attr("disabled", "true");
	button.val("Friending...");
	$.ajax({
		type: "post",
		url: "/users/" + user_id + "/friendship",
		success: function () {
			$(button.closest(".friend-buttons")).toggleClass("can-friend");
			$(button.closest(".friend-buttons")).toggleClass("can-unfriend");
			button.removeAttr("disabled");
			button.val("Friend");
		}
	});
});

$(".unfriend").on("click", function (event) {
	var button = $(event.currentTarget);
	var user_id = button.data("id");
	button.attr("disabled", "true");
	button.val("Unfriending...");
	$.ajax({
		type: "delete",
		url: "/users/" + user_id + "/friendship",
		success: function () {
			$(button.closest(".friend-buttons")).toggleClass("can-friend");
			$(button.closest(".friend-buttons")).toggleClass("can-unfriend");
			button.removeAttr("disabled");
			button.val("Unfriend");
		}
	});
});
</script>

SecretShareAjax/app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

SecretShareAjax/app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h2>Secrets</h2>
<div id="secrets">
	<% if @user.id == current_user.id %>
		<% secrets = @user.received_secrets %>
	<% else %>
		<% secrets = current_user.secrets_sent(@user) %>
	<% end %>
  <% secrets.each do |secret| %>
    <div class="secret">
			<h3><%= secret.title %></h3><span class="author">(from <%= secret.author.username %>)</span><br>
			<% secret.tags.pluck(:name).each do |tag| %>
			<span class="tag"><%= tag %></span>
			<% end %>
		</div>
  <% end %>
</div>

<div id="secret-form-box">
	<h3>Tell a secret</h3>
<%= render 'secrets/form', user_id: @user_id %>
</div>